### ISSUE TITLE
lscpu 2.38 crashing with seg fault on aarch64_cortex-53

### ISSUE THREAD

**Issue by efahl** [util-linux/util-linux#1810]
Recent OpenWrt install seg faults with all the parameter combinations I've tested (except -h and -V, they work fine).  Reported on https://github.com/openwrt/openwrt/issues/10737, where it's felt to be an upstream issue.

```
$ cat /etc/os-release
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r20614-c27279dc26"
OPENWRT_BOARD="mediatek/mt7622"
OPENWRT_ARCH="aarch64_cortex-a53"
OPENWRT_TAINTS=""
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt SNAPSHOT r20614-c27279dc26"

$ opkg install lscpu
Package lscpu (2.38-2) installed in root is up to date.

$ lscpu -V
lscpu from util-linux 2.38

$ lscpu
Segmentation fault

$ strace lscpu
execve("/usr/bin/lscpu", ["lscpu"], 0x7fe684d110 /* 15 vars */) = 0
set_tid_address(0x7f8f939248)           = 6160
brk(NULL)                               = 0x2980f000
brk(0x29811000)                         = 0x29811000
mmap(0x2980f000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2980f000
openat(AT_FDCWD, "/etc/ld-musl-aarch64.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libsmartcols.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/libsmartcols.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libsmartcols.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=98307, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0`R\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 167936, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f8f879000
mmap(0x7f8f8a0000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x17000) = 0x7f8f8a0000
close(3)                                = 0
openat(AT_FDCWD, "/lib/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=73744, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\0-\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 143360, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f8f856000
mmap(0x7f8f877000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x11000) = 0x7f8f877000
close(3)                                = 0
mprotect(0x7f8f8a0000, 4096, PROT_READ) = 0
mprotect(0x7f8f877000, 4096, PROT_READ) = 0
mprotect(0x428000, 4096, PROT_READ)     = 0
ioctl(1, TIOCGWINSZ, {ws_row=60, ws_col=200, ws_xpixel=2200, ws_ypixel=1200}) = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92e000
openat(AT_FDCWD, "/sys/devices/system/cpu", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
openat(3, "kernel_max", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
read(4, "1\n", 1024)                    = 2
lseek(4, -1, SEEK_CUR)                  = 1
close(4)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(3, "possible", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
read(4, "0-1\n", 1024)                  = 4
close(4)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(3, "present", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
read(4, "0-1\n", 1024)                  = 4
close(4)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(3, "online", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
read(4, "0-1\n", 1024)                  = 4
close(4)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(AT_FDCWD, "/proc", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
openat(4, "cpuinfo", O_RDONLY|O_LARGEFILE) = 5
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
read(5, "processor\t: 0\nBogoMIPS\t: 25.00\nF"..., 1024) = 374
read(5, "", 1024)                       = 0
close(5)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
uname({sysname="Linux", nodename="panther", ...}) = 0
personality(PER_LINUX32)                = 0 (PER_LINUX)
personality(PER_LINUX)                  = 0x8 (PER_LINUX32)
openat(3, "dispatching", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(3, "cpufreq/boost", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(4, "sysinfo", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
openat(3, "vulnerabilities", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
fstat(5, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
fcntl(5, F_GETFL)                       = 0x20000 (flags O_RDONLY|O_LARGEFILE)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92c000
fcntl(5, F_SETFD, FD_CLOEXEC)           = 0
getdents64(5, 0x7f8f92c098 /* 13 entries */, 2048) = 416
getdents64(5, 0x7f8f92c098 /* 0 entries */, 2048) = 0
lseek(5, 0, SEEK_SET)                   = 0
getdents64(5, 0x7f8f92c098 /* 13 entries */, 2048) = 416
openat(3, "vulnerabilities/spectre_v2", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/itlb_multihit", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/mmio_stale_data", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/mds", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/l1tf", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/spec_store_bypass", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/tsx_async_abort", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/spectre_v1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Mitigation: __user pointer sanit"..., 1023) = 40
read(6, "", 983)                        = 0
close(6)                                = 0
openat(3, "vulnerabilities/retbleed", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/srbds", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
openat(3, "vulnerabilities/meltdown", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
read(6, "Not affected\n", 1023)         = 13
read(6, "", 1010)                       = 0
close(6)                                = 0
close(5)                                = 0
munmap(0x7f8f92c000, 8192)              = 0
openat(AT_FDCWD, "/sys/devices/system/node", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
faccessat(3, "cpu0/topology/thread_siblings", F_OK) = 0
openat(3, "cpu0/topology/thread_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(5, F_SETFD, FD_CLOEXEC)           = 0
read(5, "", 1024)                       = 0
close(5)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(3, "cpu0/topology/core_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(5, F_SETFD, FD_CLOEXEC)           = 0
read(5, "", 1024)                       = 0
close(5)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(3, "cpu0/topology/book_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(3, "cpu0/topology/drawer_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
faccessat(3, "cpu1/topology/thread_siblings", F_OK) = 0
openat(3, "cpu1/topology/thread_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(5, F_SETFD, FD_CLOEXEC)           = 0
read(5, "", 1024)                       = 0
close(5)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(3, "cpu1/topology/core_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f92d000
fcntl(5, F_SETFD, FD_CLOEXEC)           = 0
read(5, "", 1024)                       = 0
close(5)                                = 0
munmap(0x7f8f92d000, 4096)              = 0
openat(3, "cpu1/topology/book_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(3, "cpu1/topology/drawer_siblings", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x10} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by mator** [comment]
is it possible to upload somewhere archive file with `/proc/cpuinfo` and `/sys/devices/system/cpu` ? 
`tar -vzf aarch64_cortex-a53.tar.gz /proc/cpuinfo /sys/devices/system/cpu`

**Comment by efahl** [comment]
[aarch64_cortex-a53.tar.gz](https://github.com/util-linux/util-linux/files/9587029/aarch64_cortex-a53.tar.gz)

Got some errors creating the archive, but when I untar it on another machine, it mostly seems ok.  Let me know if it needs more.

```
$ tar -czf aarch64_cortex-a53.tar.gz /proc/cpuinfo /sys/devices/system/cpu/
...
tar: /sys/devices/system/cpu/power/autosuspend_delay_ms: Read error at byte 0, while reading 1024 bytes: I/O error
...
tar: /sys/devices/system/cpu/cpu0/power/autosuspend_delay_ms: Read error at byte 0, while reading 4096 bytes: I/O error
...
tar: Exiting with failure status due to previous errors
```

**Comment by neheb** [comment]
/proc/cpuinfo is empty.

**Comment by efahl** [comment]
Tar doesn't like that device file, it treats it as zero length (as ls shows, below).  Any ideas?  The device has a pretty minimal tool set (OpenWrt with busybox), although I did install full GNU tar (v 1.34).

```
$ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 25.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 25.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

$ tar cvfz cpuinfo.tar.gz /proc/cpuinfo
tar: Removing leading `/' from member names
/proc/cpuinfo

$ tar --list -vzf cpuinfo.tar.gz
-r--r--r-- root/root         0 2022-09-15 15:25 proc/cpuinfo

$ ls -laF /proc/cpuinfo
-r--r--r--    1 root     root             0 Sep 15 15:25 /proc/cpuinfo
```

**Comment by karelzak** [comment]
@efahl, there is a script to generate proper dump from /sys and /proc, see:
https://raw.githubusercontent.com/util-linux/util-linux/master/tests/ts/lscpu/mk-input.sh

**Comment by karelzak** [comment]
It would be nice to have complate /sys and /proc dump froum your system (see my previous comment). Or you're not able to run the script, then at least try:
```
for x in $(ls /sys/devices/system/cpu/cpu*/topology/*_siblings); do echo $x; cat $x; done
```

I did a small change to the code, but not sure if it helps.

**Comment by efahl** [comment]
@karelzak, thanks for the script.  I had to hack it up a bunch to work with busybox, but I did get it to work (mostly, there is no --parents on cp, so I did 'mkdir X; cd X' for all of the subdirs).  

Ultimately, cp failed on four files (tried to cat them also, same failures):
```
/sys/devices/system/cpu/power/autosuspend_delay_ms
cp: read error: I/O error
/sys/devices/system/cpu/cpu1/power/autosuspend_delay_ms
cp: read error: I/O error
/sys/devices/system/cpu/cpufreq/policy0/stats/reset
cp: can't open '/sys/devices/system/cpu/cpufreq/policy0/stats/reset': Permission denied
/sys/devices/system/cpu/cpu0/power/autosuspend_delay_ms
cp: read error: I/O error
```

All of the rest looks good, though, here it is:
[aarch64_cortex-a53.tar.gz](https://github.com/util-linux/util-linux/files/9600030/aarch64_cortex-a53.tar.gz)

**Comment by ynezz** [comment]
I think, that the issue is empty `thread_siblings` file on kernel 5.15, probably caused by commit bb9ec13d156e ("topology: use bin_attribute to break the size limitation of cpumap ABI") introduced in kernel v5.14-rc5.

Here is a backtrace:

```
#0  get_meta (p=p@entry=0x7ff7f67c00 "") at src/malloc/mallocng/meta.h:141
#1  0x0000007ff7f93a78 in __libc_free (p=0x7ff7f67c00) at src/malloc/mallocng/free.c:105
#2  0x0000007ff7f82234 in free (p=<optimized out>) at src/malloc/free.c:5
#3  0x0000000000408f30 in add_cpuset_to_array (setsize=<optimized out>, set=<optimized out>, items=<optimized out>, ary=<optimized out>) at ../sys-utils/lscpu-topology.c:29
#4  0x00000000004093ac in cputype_read_topology (cxt=cxt@entry=0x7ff7fffe70, ct=0x4298a0) at ../sys-utils/lscpu-topology.c:153
#5  0x0000000000409b08 in lscpu_read_topology (cxt=cxt@entry=0x7ff7fffe70) at ../sys-utils/lscpu-topology.c:629
#6  0x0000000000403b60 in main (argc=1, argv=0x7ffffffdb8) at ../sys-utils/lscpu.c:1341
```

**Comment by ynezz** [comment]
Seems to be fixed with #1821.

**Comment by ynezz** [comment]
> I think, that the issue is empty `thread_siblings` file on kernel 5.15, probably caused by commit [bb9ec13d156e](https://github.com/torvalds/linux/commit/bb9ec13d156e) ("topology: use bin_attribute to break the size limitation of cpumap ABI") introduced in kernel v5.14-rc5.

@gregkh I'm not sure if it's worth investing time to fix this on kernel side as well, on 5.10 that `thread_siblings` returns number, on 5.15 it doesn't return anything. To me it looks like regression, but would like to know your opinion on that before digging deeper.

**Comment by gregkh** [comment]
why is `thread_siblings ` suddenly empty?  The kernel change did not change the contents of the files, are you looking at the size before reading from it?

Also be sure you are using the latest 5.15.y release, as there was some size problems with these binary files that have been since resolved that you might be tripping over instead.

**Comment by ynezz** [comment]
> Also be sure you are using the latest 5.15.y release, as there was some size problems with these binary files that have been since resolved that you might be tripping over instead.

Is .68 good enough or I should retry with .59?

```
root@OpenWrt:/# uname -a
Linux OpenWrt 5.15.68 #0 SMP Wed Sep 21 05:54:21 2022 aarch64 GNU/Linux

root@OpenWrt:/# find /sys -name thread_siblings -exec ls -al {} \;
-r--r--r--    1 root     root     18446744073709551615 Sep 22 08:37 /sys/devices/system/cpu/cpu1/topology/thread_siblings
-r--r--r--    1 root     root     18446744073709551615 Sep 22 08:37 /sys/devices/system/cpu/cpu0/topology/thread_siblings

root@OpenWrt:/# find /sys -name thread_siblings -exec cat {} \;
root@OpenWrt:/# 
```

**Comment by ynezz** [comment]
> @gregkh Is .68 good enough or I should retry with .69?

Answering that myself, if you're referring to commit [799e39edb0a8](https://github.com/torvalds/linux/commit/799e39edb0a8) ("drivers/base: fix userspace break from using bin_attributes for cpumap and cpulist") then is should be there since v5.15.64.

**Comment by gregkh** [comment]
Ah, looks like the patch has not made it in yet, gotta love the size of that file :(

The fix is here:
https://lore.kernel.org/r/20220906203542.1796629-1-pauld@redhat.com

But looks like it is on a slow-path to Linus's tree.  I'll go add it to my branch to get it there sooner...

**Comment by gregkh** [comment]
Ok, file size aside, what is the contents of that file on 5.10.y and now on 5.15.y?  They should be the same unless something changed in the CPU detection logic.

**Comment by ynezz** [comment]
> Ok, file size aside, what is the contents of that file on 5.10.y and now on 5.15.y? They should be the same unless something changed in the CPU detection logic.

On 5.15.68 it's empty, at least according to cat/hexdump:

```
root@OpenWrt:/# find /sys -name thread_siblings -exec cat {} \;
root@OpenWrt:/# 
```

On 5.10.138 it's all good:

```
root@OpenWrt:/# uname -a
Linux OpenWrt 5.10.138 #0 SMP Sat Sep 3 02:55:34 2022 aarch64 GNU/Linux

root@OpenWrt:/# find /sys -name thread_siblings -exec cat {} \;
2
1

root@OpenWrt:/# find /sys -name thread_siblings -exec ls -al {} \;
-r--r--r--    1 root     root          4096 Sep 22 11:12 /sys/devices/system/cpu/cpu1/topology/thread_siblings
-r--r--r--    1 root     root          4096 Sep 22 11:12 /sys/devices/system/cpu/cpu0/topology/thread_siblings
```

**Comment by gregkh** [comment]
Ok, that's a kernel issue.  Can you all send this information to the proper kernel people (Phil Auld <pauld@redhat.com>, Yury Norov <yury.norov@gmail.com>, me, and "Rafael J. Wysocki" <rafael@kernel.org>) and the linux-kernel@vger.kernel.org list and we can work on it there.

**Comment by ynezz** [comment]
>  Can you all send this information to the proper kernel people

https://lore.kernel.org/lkml/20220922113217.GA90426@meh.true.cz/T/#u

**Comment by gregkh** [comment]
Fix is now in Linus's tree, I'll go apply it to the stable trees now and it will show up in a release next week, thanks for testing!

**Comment by efahl** [comment]
Final comment: tested on kernel 5.15.71 with lscpu 2.38 and it works as expected.  Thanks to all.
