### ISSUE TITLE
new libmount-mountfd api is incompatible with python libmount

### ISSUE THREAD

**Issue by asavah** [util-linux/util-linux#1992]
Python libmount fails if libmount was built with mountfd api.

```
    ctx = libmount.Context()
    ctx.fstype="overlay"
    ctx.source="overlay"
    lower = ":".join("{:x}".format(x) for x in range(int(yamldata["maxidx"])))
    ctx.options="lowerdir={},upperdir={},workdir={}".format(lower, yamldata["upper"], yamldata["work"])
    ctx.target=yamldata["target"]
    ctx.mount()
```

```
Traceback (most recent call last):
  File "/home/asavah/kross/kbs/overmount.py", line 61, in <module>
    main()
  File "/home/asavah/kross/kbs/overmount.py", line 51, in main
    __do_mount(options.mount)
  File "/home/asavah/kross/kbs/overmount.py", line 27, in __do_mount
    ctx.mount()
TypeError: Invalid argument
```

Building util-linux with `--disable-libmount-mountfd-support` works as intended.

**Comment by asavah** [comment]
Sorry I haven't had time to investigate further and then I forgot about this ...
Currently as far as I can tell everything is working fine without using `--disable-libmount-mountfd-support`.

Sorry for the noise.

**Comment by asavah** [comment]
Same with debug enabled:

```
asavah@kross-1910:~/kross/tmp/asusb450eg/src$ sudo LIBMOUNT_DEBUG=all python
Python 3.11.2 (main, Mar 19 2023, 17:06:46) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libmount
2470478: libmount:     INIT: library debug mask: 0xffffff
2470478: libmount:     INIT: library version: 2.39.0
2470478: libmount:     INIT:     feature: btrfs
2470478: libmount:     INIT:     feature: namespaces
2470478: libmount:     INIT:     feature: idmapping
2470478: libmount:     INIT:     feature: fd-based-mount
2470478: libmount:     INIT:     feature: assert
2470478: libmount:     INIT:     feature: debug
Available "LIBMOUNT_DEBUG=<name>[,...]|<mask>" debug masks:
   all      [0xffffff] : info about all subsystems
   cache    [0x000004] : paths and tags cache
   cxt      [0x000200] : library context (handler)
   diff     [0x000400] : mountinfo changes tracking
   fs       [0x000040] : FS abstraction
   help     [0x000001] : this help
   hook     [0x008000] : hooks functionality
   locks    [0x000010] : mtab and utab locking
   loop     [0x002000] : loop devices routines
   options  [0x000008] : mount options parsing
   optlist  [0x010000] : mount options container
   tab      [0x000020] : fstab, mtab, mountinfo routines
   update   [0x000080] : mtab, utab updates
   utils    [0x000100] : misc library utils
   monitor  [0x000800] : mount tables monitor
   btrfs    [0x001000] : btrfs specific routines
   verity   [0x004000] : verity specific routines
>>> ctx = libmount.Context()
2470478: libmount:      CXT: [0x5602e8294fb0]: ----> allocate
2470478: libmount:  OPTLIST: [0x5602e8327c40]: alloc
2470478: libmount:  OPTLIST: [0x5602e8327c40]: registr map 0x7fbeb06bb2a0
2470478: libmount:  OPTLIST: [0x5602e8327c40]: registr map 0x7fbeb06bb0a0
2470478: libmount:  OPTLIST: [0x5602e8327c40]: set 0x00000000
2470478: libmount:  OPTLIST: [0x5602e8327c40]: append 0x00000000
>>> ctx.fstype="overlay"
2470478: libmount:       FS: [0x5602e82db360]: alloc
>>> ctx.source="overlay"
>>> ctx.target="/home/asavah/kross/build/asusb450eg/rootfs"
>>> ctx.options="rw,lowerdir=0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61,upperdir=/home/asavah/kross/tmp/asusb450eg/upper,workdir=/tmp/kw"
2470478: libmount:  OPTLIST: [0x5602e8327c40]: set rw,lowerdir=0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61,upperdir=/home/asavah/kross/tmp/asusb450eg/upper,workdir=/tmp/kw
2470478: libmount:  OPTLIST: [0x5602e8327c40]:  added rw [id=0x00000001 map=0x7fbeb06bb2a0]
2470478: libmount:  OPTLIST: [0x5602e8327c40]:  added lowerdir
2470478: libmount:  OPTLIST: [0x5602e8327c40]:  added upperdir
2470478: libmount:  OPTLIST: [0x5602e8327c40]:  added workdir
>>> ctx.mount()
2470478: libmount:      CXT: [0x5602e8294fb0]: mount: preparing
2470478: libmount:      CXT: [0x5602e8294fb0]: use default optsmode
2470478: libmount:  OPTLIST: [0x5602e8327c40]: return flags 0x00000000 [map=0x7fbeb06bb2a0]
2470478: libmount:      CXT: [0x5602e8294fb0]: OPTSMODE (file-part): force=0, fstab=1, mtab=1
2470478: libmount:      CXT: [0x5602e8294fb0]: fstab not required -- skip
2470478: libmount:  OPTLIST: [0x5602e8327c40]: merging
2470478: libmount:      CXT: [0x5602e8294fb0]: mount: evaluating permissions
2470478: libmount:  OPTLIST: [0x5602e8327c40]: return flags 0x00000000 [map=0x7fbeb06bb0a0]
2470478: libmount:      CXT: [0x5602e8294fb0]: perms: superuser
2470478: libmount:      CXT: [0x5602e8294fb0]: --> preparing options
2470478: libmount:      CXT: [0x5602e8294fb0]: ---> stage:prep-options
2470478: libmount:      CXT: [0x5602e8294fb0]: calling __idmap [first]
2470478: libmount:      CXT: [0x5602e8294fb0]: calling __owner [first]
2470478: libmount:      CXT: [0x5602e8294fb0]: <--- stage:prep-options [rc=0 status=1]
2470478: libmount:      CXT: [0x5602e8294fb0]: <-- preparing options done [rc=0]
2470478: libmount:      CXT: [0x5602e8294fb0]: --> preparing source path
2470478: libmount:      CXT: [0x5602e8294fb0]: srcpath 'overlay'
2470478: libmount:    CACHE: [0x5602e82f8730]: alloc
2470478: libmount:      CXT: [0x5602e8294fb0]: REMOUNT/BIND/MOVE/pseudo FS source: overlay
2470478: libmount:      CXT: [0x5602e8294fb0]: --> preparing fstype
2470478: libmount:      CXT: [0x5602e8294fb0]: FS type: overlay [rc=0]
2470478: libmount:      CXT: [0x5602e8294fb0]: --> preparing target path
2470478: libmount:    CACHE: [0x5602e82f8730]: canonicalize path /home/asavah/kross/build/asusb450eg/rootfs
2470478: libmount:    CACHE: [0x5602e82f8730]: add entry [ 1] (path): /home/asavah/kross/build/asusb450eg/rootfs: /home/asavah/kross/build/asusb450eg/rootfs
2470478: libmount:      CXT: [0x5602e8294fb0]: ---> stage:prep-target
2470478: libmount:      CXT: [0x5602e8294fb0]: calling __mkdir [first]
2470478: libmount:      CXT: [0x5602e8294fb0]: calling __subdir [first]
2470478: libmount:      CXT: [0x5602e8294fb0]: <--- stage:prep-target [rc=0 status=1]
2470478: libmount:      CXT: [0x5602e8294fb0]: final target '/home/asavah/kross/build/asusb450eg/rootfs' [rc=0]
2470478: libmount:      CXT: [0x5602e8294fb0]: checking for helper
2470478: libmount:      CXT: [0x5602e8294fb0]: /home/asavah/kross/host/sbin/mount.overlay ... not found
2470478: libmount:      CXT: [0x5602e8294fb0]: /home/asavah/kross/host/bin/mount.overlay ... not found
2470478: libmount:      CXT: [0x5602e8294fb0]: /sbin/mount.overlay       ... not found
2470478: libmount:      CXT: [0x5602e8294fb0]: /usr/sbin/mount.overlay   ... not found
2470478: libmount:      CXT: [0x5602e8294fb0]: /bin/usr/bin/mount.overlay ... not found
2470478: libmount:      CXT: [0x5602e8294fb0]: ---> stage:prep
2470478: libmount:      CXT: [0x5602e8294fb0]: calling __mount [first]
2470478: libmount:     HOOK: [0x7fbeb06bb540]: prepare mount
2470478: libmount:  OPTLIST: [0x5602e8327c40]: return flags 0x00000000 [map=0x7fbeb06bb2a0]
2470478: libmount:  OPTLIST: [0x5602e8327c40]:  clr: rw
2470478: libmount:  OPTLIST: [0x5602e8327c40]: return attrs set=0x00000000, clr=0x00000001
2470478: libmount:     HOOK: [0x7fbeb06bb540]: initialize API fds
2470478: libmount:      CXT: [0x5602e8294fb0]:  alloc '__mount' data
2470478: libmount:     HOOK:  new FS 'overlay'
2470478: libmount:     HOOK:  fsopen(overlay)
2470478: libmount:      CXT: syscall 'fsopen' [succes]
2470478: libmount:      CXT: [0x5602e8294fb0]:  appending mount hook from __mount
2470478: libmount:      CXT: [0x5602e8294fb0]:  appending mount hook from __mount
2470478: libmount:      CXT: [0x5602e8294fb0]:  appending post-mount hook from __mount
2470478: libmount:     HOOK: [0x7fbeb06bb540]: prepare mount done [rc=0]
2470478: libmount:      CXT: [0x5602e8294fb0]: calling __legacy-mount [first]
2470478: libmount:      CXT: [0x5602e8294fb0]: <--- stage:prep [rc=0 status=0]
2470478: libmount:      CXT: [0x5602e8294fb0]: --> prepare update
2470478: libmount:      CXT: [0x5602e8294fb0]: utab path initialized to: /run/mount/utab
2470478: libmount:      CXT: [0x5602e8294fb0]: checking for writable tab files
2470478: libmount:    UTILS: utab: /run/mount/utab
2470478: libmount:    UTILS: try write /run/mount/utab dir: (null)
2470478: libmount:    UTILS:  access OK
2470478: libmount:   UPDATE: [0x5602e828d190]: allocate
2470478: libmount:  OPTLIST: [0x5602e8327c40]: return flags 0x00000000 [map=0x7fbeb06bb2a0]
2470478: libmount:   UPDATE: [0x5602e828d190]: resetting FS [target=(null), flags=0x00000000]
2470478: libmount:   UPDATE: [0x5602e828d190]: FS template:
2470478: libmount:   UPDATE: 2470478: libmount:       FS: [0x5602e82db360]: synced: vfs: 'rw' fs: 'lowerdir=0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61,upperdir=/home/asavah/kross/tmp/asusb450eg/upper,workdir=/tmp/kw' user: '(null)', optstr: 'rw,lowerdir=0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61,upperdir=/home/asavah/kross/tmp/asusb450eg/upper,workdir=/tmp/kw'
------ fs:
source: overlay
target: /home/asavah/kross/build/asusb450eg/rootfs
fstype: overlay
optstr: rw,lowerdir=0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61,upperdir=/home/asavah/kross/tmp/asusb450eg/upper,workdir=/tmp/kw
VFS-optstr: rw
FS-opstr: lowerdir=0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61,upperdir=/home/asavah/kross/tmp/asusb450eg/upper,workdir=/tmp/kw
2470478: libmount:   UPDATE: prepare utab entry
2470478: libmount:   UPDATE: utab entry unnecessary (no options)
2470478: libmount:      CXT: [0x5602e8294fb0]: mount: do mount
2470478: libmount:      CXT: [0x5602e8294fb0]: ---> stage:pre-mount
2470478: libmount:      CXT: [0x5602e8294fb0]: <--- stage:pre-mount [rc=0 status=0]
2470478: libmount:      CXT: [0x5602e8294fb0]: ---> stage:mount
2470478: libmount:      CXT: [0x5602e8294fb0]: calling __mount [active]
2470478: libmount:     HOOK: [0x7fbeb06bb540]: init FS
2470478: libmount:      CXT: syscall 'fsconfig' [succes]
2470478: libmount:     HOOK: [0x7fbeb06bb540]:  config FS
2470478: libmount:     HOOK: [0x7fbeb06bb540]:   fsconfig(name=rw,value=(null))
2470478: libmount:      CXT: syscall 'fsconfig' [succes]
2470478: libmount:     HOOK: [0x7fbeb06bb540]:   fsconfig(name=lowerdir,value=0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61)
2470478: libmount:      CXT: syscall 'fsconfig' [Invalid argument]
2470478: libmount:     HOOK: [0x7fbeb06bb540]: create FS done [rc=-22, id=0]
2470478: libmount:      CXT: [0x5602e8294fb0]: <--- stage:mount [rc=-22 status=-22]
2470478: libmount:      CXT: [0x5602e8294fb0]: mnt_context_do_mount() done [rc=-22]
2470478: libmount:     HOOK: [0x7fbeb06bb600]: deinit '__loopdev'
2470478: libmount:     HOOK: [0x7fbeb06bb580]: deinit '__mkdir'
2470478: libmount:     HOOK: [0x7fbeb06bb5a0]: deinit '__subdir'
2470478: libmount:     HOOK: [0x7fbeb06bb540]: deinit '__mount'
2470478: libmount:      CXT: [0x5602e8294fb0]:  removing mount hook from __mount
2470478: libmount:      CXT: [0x5602e8294fb0]:  removing mount hook from __mount
2470478: libmount:      CXT: [0x5602e8294fb0]:  removing post-mount hook from __mount
2470478: libmount:      CXT: [0x5602e8294fb0]:  free '__mount' data
2470478: libmount:     HOOK: [0x7fbeb06bb560]: deinit '__legacy-mount'
2470478: libmount:     HOOK: [0x7fbeb06bb5e0]: deinit '__idmap'
2470478: libmount:     HOOK: [0x7fbeb06bb5c0]: deinit '__owner'
2470478: libmount:      CXT: [0x5602e8294fb0]: mnt_context_mount() done [rc=-22]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Invalid argument
```

**Comment by asavah** [comment]
Probably a limit set here https://github.com/torvalds/linux/blob/master/fs/fsopen.c#L397
because "256 ought to be enough for anybody" (c)

**Comment by asavah** [comment]
Thx, what I posted is a simplified real use case, I know that there are limtations like PATH_MAX and ARG_MAX.
That's why I made the script in python which first creates a bunch of short symlinks (0:1:2:...) to the real much longer paths and the feeds the resulting bunch of symlinks as lower= to overlayfs. If I used real absolute paths that lower= would be insanely long.

I would rather not try to deal with kernel folks, the entry level to that club to even report a bug is too high for me.
I would appreciate if anyone familiar with kernel mailing lists reported this.

**Comment by brauner** [comment]
> Thx, what I posted is a simplified real use case, I know that there are limtations like PATH_MAX and ARG_MAX. That's why I made the script in python which first creates a bunch of short symlinks (0:1:2:...) to the real much longer paths and the feeds the resulting bunch of symlinks as lower= to overlayfs. If I used real absolute paths that lower= would be insanely long.
> 
> This actually limits a lot how overlayfs can be used, for example if someone used a bunch of absolute paths eg `lower=/home/username/project/data1:/home/username/project/data2:/home/username/project/dataN` they would hit the limit real quick which makes usage of fsconfig api in mount undesirable at least for overlayfs.
> 
> I would rather not try to deal with kernel folks, the entry level to that club to even report a bug is too high for me. I would appreciate if anyone familiar with kernel mailing lists reported this.

I'll try to get that fixed. This seems like a legitimate problem. Might take until next week though.

**Comment by asavah** [comment]
> > Thx, what I posted is a simplified real use case, I know that there are limtations like PATH_MAX and ARG_MAX. That's why I made the script in python which first creates a bunch of short symlinks (0:1:2:...) to the real much longer paths and the feeds the resulting bunch of symlinks as lower= to overlayfs. If I used real absolute paths that lower= would be insanely long.
> > This actually limits a lot how overlayfs can be used, for example if someone used a bunch of absolute paths eg `lower=/home/username/project/data1:/home/username/project/data2:/home/username/project/dataN` they would hit the limit real quick which makes usage of fsconfig api in mount undesirable at least for overlayfs.
> > I would rather not try to deal with kernel folks, the entry level to that club to even report a bug is too high for me. I would appreciate if anyone familiar with kernel mailing lists reported this.
> 
> I'll try to get that fixed. This seems like a legitimate problem. Might take until next week though.

Thank you for taking a look into this, appreciate it.

**Comment by brauner** [comment]
So I looked into this today. The reason why we consider 256 bytes enough is that mount options can be specified differently than in the old mount api. So in the old mount api you have needed to specify all mount options as a single string and pass that to `mount(2)`. In the new mount api you can split setting mount options. So you would do:

```c
int main(int argc, char *argv[])
{
        int mnt_fd, fs_fd, ret, tree_fd;

        fs_fd = fsopen("overlay", FSOPEN_CLOEXEC);
        if (fs_fd < 0)
                die_errno("Failed to create overlay context");

        ret = fsconfig(fs_fd, FSCONFIG_SET_STRING, "upperdir", "/home/asavah/kross/tmp/asusb450eg/upper", 0);
        if (ret < 0)
                die_errno("fsconfig: set upperdir");

        ret = fsconfig(fs_fd, FSCONFIG_SET_STRING, "workdir", "/tmp/kw", 0);
        if (ret < 0)
                die_errno("fsconfig: set workdir");

        ret = fsconfig(fs_fd, FSCONFIG_SET_STRING, "lowerdir", "0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:
        if (ret < 0)
                die_errno("fsconfig: set workdir");

        ret = fsconfig(fs_fd, FSCONFIG_CMD_CREATE, NULL, NULL, 0);
        if (ret < 0)
                die_errno("fsconfig: create");

        mnt_fd = fsmount(fs_fd, 0, 0);
        if (mnt_fd < 0)
                die_errno("fsmount");

        ret = move_mount(mnt_fd, "", -EBADF, "/home/asavah/kross/build/asusb450eg/rootfs",
                         MOVE_MOUNT_F_EMPTY_PATH);
        if (ret < 0)
                die_errno("move_mount");

        exit(EXIT_SUCCESS);
}
```

However, as you correctly point out, there's an additional problem if e.g., the `lowerdir` mount option takes multiple parameters. Currently you need to specify `lowerdir=` exactly one time. But that's only because overlayfs hasn't been ported to the new mount api yet. Once that's done you can just specify:

```c
ret = fsconfig(fs_fd, FSCONFIG_SET_STRING, "lowerdir", "/home/username/project/data1", 0);
if (ret < 0)
        die_errno("fsconfig: set lowerdir");

ret = fsconfig(fs_fd, FSCONFIG_SET_STRING, "lowerdir", "/home/username/project/data2", 0);
if (ret < 0)
        die_errno("fsconfig: set lowerdir");

ret = fsconfig(fs_fd, FSCONFIG_SET_STRING, "lowerdir", "/home/username/project/data3", 0);
if (ret < 0)
        die_errno("fsconfig: set lowerdir");

/*
 * .
 * .
 * .
 *
 * The total limit is 2 * PAGE_SIZE btw.
 */

ret = fsconfig(fs_fd, FSCONFIG_SET_STRING, "lowerdir", "/home/username/project/dataN", 0);
if (ret < 0)
        die_errno("fsconfig: set lowerdir");
```

So I'd rather fix overlayfs by porting it to the new mount api rather than encouraging hacking this all into one string by expanding the buffer.

**Comment by karelzak** [comment]
This is probably another example of when some env. variable to use the old API in libmount (something like LIBMOUNT_FORCE_MOUNT2=yes) would be useful as a temporary workaround.

**Comment by Andrei-Pozolotin** [comment]
this now trickles down into archlinux:
https://bugs.archlinux.org/task/78702

**Comment by Andrei-Pozolotin** [comment]
@brauner 

> So I'd rather fix overlayfs by porting it to the new mount api rather than encouraging hacking this all into one string by expanding the buffer.

1) there is NO mention of this issue in `kernel bugs / overlayfs`:

https://bugzilla.kernel.org/buglist.cgi?bug_status=__open__&content=overlayfs&no_redirect=1&order=changeddate%20DESC%2Cpriority%2Cbug_severity&query_format=specific

2) can you please file a proper / meaningful bug report there?

3) who / where can we find / ping people who might help resolve this issue? thank you.

**Comment by thesamesam** [comment]
He probably _is_ the relevant person.
