### ISSUE TITLE
Heap-buffer-overflow in `findmnt` when showing the `SOURCES` column

### ISSUE THREAD

**Issue by mrc0mmand** [util-linux/util-linux#2980]
While debugging some systemd stuff on Rawhide, I accidentally stumbled across some weird output from `findmnt`:

```
# git describe
v2.41-devel-320-ga6d12b403
# build/findmnt --mountpoint /
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/vda2 ext4   rw,relatime,seclabel
# build/findmnt --mountpoint / --noheading -o SOURCES
/dev/vda2k\xf7\xbc\x9d\x7f
# build/findmnt --mountpoint / --noheading -o SOURCES
/dev/vda2\xab\xa6#}\x7f
```

This seems to happen both with the latest master and Rawhide's util-linux (`util-linux-2.40-13.fc41.x86_64`).

If I rebuild util-linux with ASan, it points to the culprit with some additional information:

```
# build-san/findmnt --mountpoint / --noheading -o SOURCES
=================================================================
==14706==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x502000001fb9 at pc 0x7f7aa527b4f6 bp 0x7fff66d42280 sp 0x7fff66d41a40
READ of size 10 at 0x502000001fb9 thread T0
    #0 0x7f7aa527b4f5 in strlen.part.0 (/lib64/libasan.so.8+0x7b4f5) (BuildId: 7022e2c258d72a038cc2b24c29899fd84453f59d)
    #1 0x7f7aa4eecd9b in scols_column_greatest_wrap ../libsmartcols/src/column.c:1026
    #2 0x7f7aa4f0bf00 in __cursor_to_buffer ../libsmartcols/src/print.c:728
    #3 0x7f7aa4f16f72 in count_cell_width ../libsmartcols/src/calculate.c:53
    #4 0x7f7aa4f18be4 in count_column_width ../libsmartcols/src/calculate.c:198
    #5 0x7f7aa4f1c3c5 in __scols_calculate ../libsmartcols/src/calculate.c:445
    #6 0x7f7aa4f123a4 in __scols_initialize_printing ../libsmartcols/src/print.c:1258
    #7 0x7f7aa4f13aa1 in do_print_table ../libsmartcols/src/print-api.c:131
    #8 0x7f7aa4f1403b in scols_print_table ../libsmartcols/src/print-api.c:172
    #9 0x410216 in main ../misc-utils/findmnt.c:1969
    #10 0x7f7aa403c1c7 in __libc_start_call_main (/lib64/libc.so.6+0x2a1c7) (BuildId: cf0dca1b5fb2e7a44f5cff6a4f42e1d9da51a90e)
    #11 0x7f7aa403c28a in __libc_start_main_alias_1 (/lib64/libc.so.6+0x2a28a) (BuildId: cf0dca1b5fb2e7a44f5cff6a4f42e1d9da51a90e)
    #12 0x405e14 in _start (/root/util-linux/build-san/findmnt+0x405e14) (BuildId: df8bac26ac40e5f8f9d3bd3dfa61eaf159cc557d)

0x502000001fb9 is located 0 bytes after 9-byte region [0x502000001fb0,0x502000001fb9)
allocated by thread T0 here:
    #0 0x7f7aa52f56a8 in realloc.part.0 (/lib64/libasan.so.8+0xf56a8) (BuildId: 7022e2c258d72a038cc2b24c29899fd84453f59d)
    #1 0x7f7aa4eec1e9 in scols_column_init_wrap ../libsmartcols/src/column.c:974
    #2 0x7f7aa4eec723 in scols_column_next_wrap ../libsmartcols/src/column.c:999
    #3 0x7f7aa4eecef3 in scols_column_greatest_wrap ../libsmartcols/src/column.c:1025
    #4 0x7f7aa4f0bf00 in __cursor_to_buffer ../libsmartcols/src/print.c:728
    #5 0x7f7aa4f16f72 in count_cell_width ../libsmartcols/src/calculate.c:53
    #6 0x7f7aa4f18be4 in count_column_width ../libsmartcols/src/calculate.c:198
    #7 0x7f7aa4f1c3c5 in __scols_calculate ../libsmartcols/src/calculate.c:445
    #8 0x7f7aa4f123a4 in __scols_initialize_printing ../libsmartcols/src/print.c:1258
    #9 0x7f7aa4f13aa1 in do_print_table ../libsmartcols/src/print-api.c:131
    #10 0x7f7aa4f1403b in scols_print_table ../libsmartcols/src/print-api.c:172
    #11 0x410216 in main ../misc-utils/findmnt.c:1969
    #12 0x7f7aa403c1c7 in __libc_start_call_main (/lib64/libc.so.6+0x2a1c7) (BuildId: cf0dca1b5fb2e7a44f5cff6a4f42e1d9da51a90e)
    #13 0x7f7aa403c28a in __libc_start_main_alias_1 (/lib64/libc.so.6+0x2a28a) (BuildId: cf0dca1b5fb2e7a44f5cff6a4f42e1d9da51a90e)
    #14 0x405e14 in _start (/root/util-linux/build-san/findmnt+0x405e14) (BuildId: df8bac26ac40e5f8f9d3bd3dfa61eaf159cc557d)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.8+0x7b4f5) (BuildId: 7022e2c258d72a038cc2b24c29899fd84453f59d) in strlen.part.0
Shadow bytes around the buggy address:
  0x502000001d00: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x502000001d80: fa fa fd fa fa fa fd fa fa fa 00 01 fa fa fd fa
  0x502000001e00: fa fa 00 02 fa fa 07 fa fa fa 05 fa fa fa 07 fa
  0x502000001e80: fa fa 04 fa fa fa 04 fa fa fa 00 02 fa fa 00 02
  0x502000001f00: fa fa 00 02 fa fa 07 fa fa fa 07 fa fa fa 02 fa
=>0x502000001f80: fa fa 02 fa fa fa 00[01]fa fa fa fa fa fa fa fa
  0x502000002000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000002080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000002100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000002180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000002200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==14706==ABORTING
```

**Comment by t-8ch** [comment]
Should be fixed by #2983
