### ISSUE TITLE
[SECURITY] Memory Leak in fsck.c

### ISSUE THREAD

**Issue by RootUp** [util-linux/util-linux#3053]
**Summary:**
The leak was identified  because a dynamically allocated memory for command-line arguments (`argv`) array is not being properly freed. 

**Code Snippet:**

Possible allocation is being leaked at 

```C
argv[argc++] = xstrdup(fs_get_device(fs));
```

**ASAN:**

```
==1433448==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x482334 in strdup (/util-linux/fsck+0x482334)
    #1 0x4ca789 in xstrdup /util-linux/./include/xalloc.h:83:8
    #2 0x4ca789 in execute /util-linux/disk-utils/fsck.c:709:15
    #3 0x4ca789 in fsck_device /util-linux/disk-utils/fsck.c:939:11
    #4 0x4c8d9e in check_all /util-linux/disk-utils/fsck.c:1356:14
    #5 0x4c7345 in main /util-linux/disk-utils/fsck.c
    #6 0x7ffff7c4c082 in __libc_start_main /build/glibc-e2p3jK/glibc-2.31/csu/../csu/libc-start.c:308:16

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x482334 in strdup (/util-linux/fsck+0x482334)
    #1 0x4ca789 in xstrdup /util-linux/./include/xalloc.h:83:8
    #2 0x4ca789 in execute /util-linux/disk-utils/fsck.c:709:15
    #3 0x4ca789 in fsck_device /util-linux/disk-utils/fsck.c:939:11
    #4 0x4c86de in check_all /util-linux/disk-utils/fsck.c:1293:15
    #5 0x4c7345 in main /util-linux/disk-utils/fsck.c
    #6 0x7ffff7c4c082 in __libc_start_main /build/glibc-e2p3jK/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 10 byte(s) leaked in 2 allocation(s).
```

**Comment by t-8ch** [comment]
The util-linux codebase does not free memory in executable at the end of main.
The memory will be cleaned up anyways upon exiting.
